name = "iphone-cost"
main = "./workers/app.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "iphone-cost.luckeverything.com", custom_domain = true }
]

[assets]
directory = "./build/client"
